Repository ooni/probe-engine, pull requests merged in 2019-10, with the labels that each got.

#62 Release v0.1.0
  LICENSE
  README.md
  cmd/miniooni/main.go
  collector/collector.go
  collector/collector_test.go
  experiment/dash/dash.go
  experiment/experiment.go
  experiment/experiment_test.go
  experiment/fbmessenger/fbmessenger.go
  experiment/handler/handler_test.go
  experiment/hhfm/hhfm.go
  experiment/hirl/hirl.go
  experiment/mkevent/mkevent.go
  experiment/mkevent/mkevent_test.go
  experiment/mkhelper/mkhelper.go
  experiment/mkhelper/mkhelper_test.go
  experiment/mkrunner/mkrunner.go
  experiment/mkrunner/mkrunner_test.go
  experiment/ndt/ndt.go
  experiment/telegram/telegram.go
  experiment/web_connectivity/web_connectivity.go
  experiment/whatsapp/whatsapp.go
  geoiplookup/iplookup/akamai/akamai.go
  geoiplookup/iplookup/invalid/invalid.go
  geoiplookup/iplookup/iplookup.go
  geoiplookup/iplookup/iplookup_test.go
  geoiplookup/mmdblookup/mmdblookup.go
  geoiplookup/mmdblookup/mmdblookup_test.go
  geoiplookup/resolverlookup/resolverlookup.go
  geoiplookup/resolverlookup/resolverlookup_test.go
  go.mod
  go.sum
  httpx/fetch/fetch_test.go
  measurementkit/task_cgo.go
  model/model.go
  model/model_test.go
  orchestra/testlists/testlists_test.go
  resources/resources.go
  resources/resources_test.go
  session/session.go
  session/session_test.go
Labels: P0, please preserve history

#74 session: expose the ProbeASN as an integer
  session/session.go
Labels: P0, bug

#61 dash: rewrite using neubot/dash
  experiment/dash/dash_cgo.go
  experiment/dash/dash_cgo_test.go
  experiment/dash/dash_otherwise.go
  experiment/dash/dash_otherwise_test.go
Labels: enhancement, hacktoberfest

#98 experiment.go: fix measurement runtime
  experiment/experiment.go
Labels: bug, priority/high

#95 Update to stable m-lab/ndt7-client-go@v0.1.0
  experiment/ndt7/ndt7.go
  go.mod
  go.sum
Labels: enhancement, priority/high
